name: ✨ Feature Request
description: Suggest a new feature for MarkView
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input in making MarkView better.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's missing?
      placeholder: I'm always frustrated when I need to export multiple files at once...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Be as detailed as possible
      placeholder: Add a "Batch Export" button that allows selecting multiple markdown files...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any other solutions or workarounds?
      placeholder: I currently export files one by one, but it's time-consuming...
  
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Are there other tools or extensions that have this feature?
      placeholder: VSCode has a similar feature where...
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
  
  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide testing and feedback
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
