name: ❓ Question
description: Ask a question about MarkView
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about how MarkView works? We're here to help!
  
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about MarkView?
      placeholder: How do I export markdown files with custom fonts?
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us answer your question?
      placeholder: I'm trying to create a document with Times New Roman font...
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have checked the documentation and FAQs
        - label: I have searched existing issues for similar questions
          required: true
